package com.yatayat.backend.entity;

public enum DriverNotificationType {
    SCHEDULED_TRIP_ASSIGNED,
    SCHEDULED_TRIP_UPDATED,
    SCHEDULED_TRIP_CANCELLED,
    LOCAL_SERVICE_ASSIGNED,
    LOCAL_SERVICE_UPDATED,
    LOCAL_SERVICE_CANCELLED,
    OPERATOR_INVITATION,
    OPERATOR_INVITATION_ACCEPTED,
    OPERATOR_INVITATION_REJECTED,
    GENERAL
}
