package com.yatayat.backend.entity;

public enum NotificationType {
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    PAYMENT_SUCCESSFUL,
    WALLET_TOP_UP_SUCCESSFUL,
    TICKET_GENERATED,
    TICKET_QR_GENERATED,
    LOCAL_FARE_QR_GENERATED,
    TICKET_USED,
    LOCAL_FARE_PASS_USED
}
