import { useEffect, useMemo, useState } from "react";
import { ArrowLeft, Loader2 } from "lucide-react";
import { useNavigate, useParams } from "react-router-dom";
import PassengerLayout from "../../components/layout/PassengerLayout";
import { createPassengerBooking, formatBookingDate, formatNpr, handleBookingSession } from "../../utils/passengerBookings";
import { passengerTripRequest } from "../../utils/passengerTrips";

export default function CreatePassengerBookingPage() {
  const { tripId } = useParams(); const navigate = useNavigate();
  const stored = localStorage.getItem("yatayatUser"); const user = stored ? JSON.parse(stored) : {};
  const [trip, setTrip] = useState(null); const [loading, setLoading] = useState(true);
  const [submitting, setSubmitting] = useState(false); const [error, setError] = useState("");
  const [form, setForm] = useState({ passengerName: user.fullName || "", passengerPhone: user.phone || "", numberOfSeats: "1" });
  useEffect(() => { let active = true; passengerTripRequest(`/api/passenger/trips/${tripId}`).then((data) => { if (active) setTrip(data); }).catch((loadError) => { if (active && !handleBookingSession(loadError, navigate)) setError(loadError.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [navigate, tripId]);
  const estimatedTotal = useMemo(() => trip ? Number(trip.fare) * Math.max(0, Number(form.numberOfSeats) || 0) : 0, [form.numberOfSeats, trip]);
  const submit = async (event) => {
    event.preventDefault(); const seats = Number(form.numberOfSeats);
    if (form.passengerName.trim().length < 2) return setError("Enter a valid passenger name.");
    if (!/^[0-9+()\-\s]{7,20}$/.test(form.passengerPhone.trim())) return setError("Enter a valid passenger phone number.");
    if (!Number.isInteger(seats) || seats <= 0) return setError("Number of seats must be a positive whole number.");
    setSubmitting(true); setError("");
    try { const booking = await createPassengerBooking({ tripId: Number(tripId), passengerName: form.passengerName.trim(), passengerPhone: form.passengerPhone.trim(), numberOfSeats: seats }); navigate(`/passenger/bookings/${booking.bookingReference}`, { replace: true, state: { created: true } }); }
    catch (submitError) { if (!handleBookingSession(submitError, navigate)) setError(submitError.message); }
    finally { setSubmitting(false); }
  };
  return <PassengerLayout activePage="Find Trips"><div className="mx-auto max-w-5xl space-y-6"><button onClick={() => navigate(`/passenger/trips/${tripId}`)} className="flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} /> Back to trip details</button><div><h1 className="text-3xl font-black text-slate-900">Create Booking</h1><p className="mt-1 text-sm text-slate-500">Confirm passenger information for this scheduled trip.</p></div>{error && <div className="rounded-2xl border border-red-200 bg-red-50 p-4 font-bold text-red-700">{error}</div>}{loading ? <div className="flex min-h-72 items-center justify-center"><Loader2 className="animate-spin" size={40} /></div> : trip && (trip.tripType === "LOCAL" ? <div className="rounded-3xl border border-amber-200 bg-amber-50 p-8"><h2 className="text-2xl font-black text-amber-900">Seat booking is not available</h2><p className="mt-2 font-semibold text-amber-800">This is a local trip. Local fare ticket support will be added in a later phase.</p><button onClick={() => navigate(`/passenger/trips/${tripId}`)} className="mt-5 rounded-xl bg-[#08264a] px-6 py-3 font-black text-white">Return to Trip Details</button></div> : <div className="grid gap-6 lg:grid-cols-[1fr_0.85fr]"><TripSummary trip={trip} /><form onSubmit={submit} className="space-y-5 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm"><Input label="Passenger name" maxLength={120} value={form.passengerName} onChange={(value) => setForm((current) => ({ ...current, passengerName: value }))} required /><Input label="Passenger phone" maxLength={20} value={form.passengerPhone} onChange={(value) => setForm((current) => ({ ...current, passengerPhone: value }))} required /><Input label="Number of seats" type="number" min="1" step="1" value={form.numberOfSeats} onChange={(value) => setForm((current) => ({ ...current, numberOfSeats: value }))} required /><div className="rounded-2xl bg-blue-50 p-4"><p className="text-xs font-black uppercase text-blue-700">Estimated total</p><p className="mt-1 text-3xl font-black text-[#08264a]">{formatNpr(estimatedTotal)}</p><p className="mt-1 text-xs text-slate-500">Calculated from the current trip fare. The backend confirms the final amount.</p></div><button disabled={submitting} className="w-full rounded-xl bg-[#08264a] py-3 font-black text-white disabled:opacity-60">{submitting ? "Creating booking..." : "Confirm Booking"}</button><p className="text-center text-xs text-slate-500">No payment, seat number, or ticket is issued in this step.</p></form></div>)}</div></PassengerLayout>;
}
function Input({ label, value, onChange, type = "text", ...props }) { return <label className="block text-sm font-black text-slate-700">{label}<input {...props} type={type} value={value} onChange={(event) => onChange(event.target.value)} className="mt-2 w-full rounded-xl border border-slate-300 px-4 py-3 font-semibold outline-none focus:border-[#08264a]" /></label>; }
function TripSummary({ trip }) { return <section className="rounded-3xl bg-[#08264a] p-6 text-white"><p className="text-sm font-bold text-blue-200">{trip.routeCode} - Outside Valley</p><h2 className="mt-1 text-2xl font-black">{trip.routeName}</h2><p className="mt-2 text-slate-300">{trip.origin} to {trip.destination}</p><div className="mt-6 space-y-3 text-sm">{[["Operator", trip.operatorName], ["Bus", `${trip.busName || "Bus"} (${trip.busNumber})`], ["Departure", formatBookingDate(trip.departureAt)], ["Arrival", formatBookingDate(trip.estimatedArrivalAt)], ["Fare per seat", formatNpr(trip.fare)], ["Bus capacity", `${trip.seatCapacity} seats`]].map(([label, value]) => <div key={label} className="flex justify-between gap-4 border-b border-white/10 pb-3"><span className="text-slate-300">{label}</span><b className="text-right">{value}</b></div>)}</div></section>; }
