import { useEffect, useState } from "react";
import { ArrowLeft, CheckCircle2, Loader2, XCircle } from "lucide-react";
import { useLocation, useNavigate, useParams } from "react-router-dom";
import { toast } from "react-toastify";
import PassengerLayout from "../../components/layout/PassengerLayout";
import { cancelPassengerBooking, formatBookingDate, formatNpr, getPassengerBooking, handleBookingSession } from "../../utils/passengerBookings";

export default function PassengerBookingDetailsPage() {
  const { bookingReference } = useParams(); const navigate = useNavigate(); const location = useLocation();
  const [booking, setBooking] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const [showCancel, setShowCancel] = useState(false); const [cancelling, setCancelling] = useState(false);
  useEffect(() => { let active = true; getPassengerBooking(bookingReference).then((data) => { if (active) setBooking(data); }).catch((loadError) => { if (active && !handleBookingSession(loadError, navigate)) setError(loadError.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [bookingReference, navigate]);
  const cancel = async () => { setCancelling(true); try { setBooking(await cancelPassengerBooking(bookingReference)); setShowCancel(false); toast.success("Booking cancelled successfully."); } catch (cancelError) { if (!handleBookingSession(cancelError, navigate)) { setError(cancelError.message); setShowCancel(false); } } finally { setCancelling(false); } };
  const cancellable = ["PENDING_PAYMENT", "CONFIRMED"].includes(booking?.bookingStatus) && new Date(booking.departureAt) > new Date();
  const rows = booking ? [["Passenger", booking.passengerName], ["Phone", booking.passengerPhone], ["Route", `${booking.routeCode} - ${booking.routeName}`], ["Trip type", booking.tripType === "LOCAL" ? "Local" : "Outside Valley"], ["Journey", `${booking.origin} to ${booking.destination}`], ["Operator", booking.operatorName], ["Bus", booking.busNumber], ["Departure", formatBookingDate(booking.departureAt)], ["Estimated arrival", formatBookingDate(booking.estimatedArrivalAt)], ["Selected seats", booking.seatNumbers?.length ? booking.seatNumbers.join(", ") : `${booking.numberOfSeats} seat(s)`], ["Fare per seat", formatNpr(booking.farePerSeat)], ["Total fare", formatNpr(booking.totalFare)], ["Booked at", formatBookingDate(booking.bookedAt)], ["Cancelled at", booking.cancelledAt ? formatBookingDate(booking.cancelledAt) : "Not cancelled"], ["Boarding notes", booking.boardingNotes || "No boarding notes provided"]] : [];
  return <PassengerLayout activePage="My Bookings"><div className="mx-auto max-w-5xl space-y-6">
    <button onClick={() => navigate("/passenger/bookings")} className="flex items-center gap-2 text-sm font-black"><ArrowLeft size={17} /> Back to My Bookings</button>
    {location.state?.created && <div className="rounded-2xl border border-amber-200 bg-amber-50 p-5 text-amber-900"><div className="flex items-center gap-2 font-black"><CheckCircle2 size={20} /> Seats reserved. Payment is pending.</div><p className="mt-2 text-sm">Payment, ticket generation, QR, and email delivery are coming next.</p></div>}
    {error && <div className="rounded-2xl border border-red-200 bg-red-50 p-5 font-bold text-red-700">{error}</div>}
    {loading ? <div className="flex min-h-72 items-center justify-center"><Loader2 className="animate-spin" size={40} /></div> : booking && <>
      <header className="flex flex-col justify-between gap-4 rounded-3xl bg-[#08264a] p-7 text-white sm:flex-row"><div><p className="text-sm font-bold text-blue-200">Booking reference</p><h1 className="mt-1 break-all text-3xl font-black">{booking.bookingReference}</h1><p className="mt-2 text-slate-300">{booking.origin} to {booking.destination}</p></div><Status value={booking.bookingStatus} /></header>
      <section className="grid grid-cols-1 gap-4 rounded-3xl border border-slate-200 bg-white p-6 shadow-sm sm:grid-cols-2">{rows.map(([label, value]) => <div key={label} className="rounded-2xl bg-slate-50 p-4"><p className="text-xs font-black uppercase tracking-wide text-slate-500">{label}</p><p className="mt-2 font-bold text-slate-800">{value}</p></div>)}</section>
      <div className="flex flex-col justify-between gap-4 rounded-2xl border border-blue-200 bg-blue-50 p-5 sm:flex-row sm:items-center"><p className="text-sm font-bold text-blue-900">Payment Coming Next. Your selected seats remain reserved with this pending booking.</p>{cancellable && <button onClick={() => setShowCancel(true)} className="flex shrink-0 items-center justify-center gap-2 rounded-xl bg-red-600 px-5 py-3 font-black text-white"><XCircle size={17} /> Cancel Booking</button>}</div>
    </>}
    {showCancel && <CancelModal cancelling={cancelling} onClose={() => setShowCancel(false)} onConfirm={cancel} />}
  </div></PassengerLayout>;
}

function Status({ value }) { const style = value === "CONFIRMED" ? "bg-emerald-400/20 text-emerald-100" : value === "PENDING_PAYMENT" ? "bg-amber-400/20 text-amber-100" : "bg-red-400/20 text-red-100"; return <span className={`self-start rounded-full px-4 py-2 text-xs font-black ${style}`}>{value}</span>; }
function CancelModal({ cancelling, onClose, onConfirm }) { return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-black/50 p-4"><div className="w-full max-w-md rounded-3xl bg-white p-6"><h2 className="text-2xl font-black">Cancel this booking?</h2><p className="mt-2 text-sm text-slate-500">It will remain in your history with a cancelled status and its seats will be released.</p><div className="mt-6 flex justify-end gap-3"><button disabled={cancelling} onClick={onClose} className="rounded-xl border border-slate-300 px-4 py-3 font-black">Keep Booking</button><button disabled={cancelling} onClick={onConfirm} className="rounded-xl bg-red-600 px-4 py-3 font-black text-white disabled:opacity-60">{cancelling ? "Cancelling..." : "Confirm Cancellation"}</button></div></div></div>; }
