spring.application.name=yatayat-backend

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/yatayat_db
spring.datasource.username=root
spring.datasource.password=root12345

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.default_schema=yatayat_db

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=Yatayat.info@gmail.com
spring.mail.password=vufblczaneftxnjy
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

spring.security.oauth2.client.registration.google.client-id=237663891339-ojpb0a1r4d768cdpv56et90dtdqhuetb.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile

driver.upload.directory=uploads/drivers

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=30MB

yatayat.admin.email=admin@yatayat.com
yatayat.admin.password=Admin@123
yatayat.admin.name=Yatayat Administrator

yatayat.cors.allowed-origins=${YATAYAT_CORS_ALLOWED_ORIGINS:http://localhost:5173}
